name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
      - uses: actions/checkout@v2
      - name: Build
        run: build.bat
